c = document.getElementById('tdacanvas')
epsilon_ = document.getElementById('epsilon')

let Chain = class Chain { // a chain is an element on the free abelian group on simplices
    constructor(simplices, signs) {
        this.simplices = simplices
        this.signs = signs
    }
}

let Point = class Point {
    constructor(idx, x, y) {
        this.idx = idx
        this.x = x
        this.y = y
    }

    boundary() {
        return null
    }
}


let nSimplex = class nSimplex { // ordered list of points
    // 0-simplex is point, 1-simplex is line, 2-simplex triangle, etc.
    // so points should be n+1 points for the n-simplex
    constructor(points) {
        this.points = points
        this.n = points.length - 1
    }

    boundary() {
        let faces = []
        let signs = []
        for (let i = 0; i < this.n; n++) {
            faces.push(this.face(i))
            signs.push(i % 2 === 0 ? 1 : -1) // -1^i in the usual formula
        }
        return new Chain(
            faces,
            signs
        )
    }

    // getting the i-th face of an n-simplex is defined as deleting the i-th vertex/point
    face(i) {
        let face_points = [...this.points]
        face_points.splice(i, i)
        return new nSimplex(face_points)
    }
}


let points = [] // 0-simplices, n-simplices generated by Cech complex.

let epsilon = 20

c.width = window.innerWidth
c.height = window.innerHeight

ctx = c.getContext("2d")

ctx.fill()


c.addEventListener('click', function (event) {
    console.log("added " + points.length + "-th point")
    // calc offsets
    let p = new Point(points.length, event.x - c.offsetLeft, event.y - c.offsetTop)
    points.push(p)
    // update
    requestAnimationFrame(do_update)
})

epsilon_.oninput = function () {
    epsilon = this.value / 50
    requestAnimationFrame(do_update)
}

function do_update(t) {
    //requestAnimationFrame(do_update)
    ctx.clearRect(0, 0, c.width, c.height)

    ctx.fillStyle = "rgb(220, 220, 220)"
    ctx.strokeStyle = "rgb(0, 0, 255)"
    for (const p of points) {
        ctx.beginPath()
        ctx.arc(p.x, p.y, epsilon, 0, 2 * Math.PI, false)
        ctx.fill()
    }
    for (const p of points) {
        ctx.beginPath()
        ctx.arc(p.x, p.y, epsilon, 0, 2 * Math.PI, false)
        ctx.stroke()
    }

    ctx.fillStyle = "rgb(0, 0, 0)"
    for (const p of points) {
        console.log('doing thing')
        ctx.beginPath()
        ctx.arc(p.x, p.y, 8, 0, 2 * Math.PI, false)
        ctx.fill()
    }

    console.log('updated')

}

requestAnimationFrame(do_update)
